# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.edi_pb2 as edi__pb2


class EDIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateShipping = channel.unary_stream(
                '/EDIService/CalculateShipping',
                request_serializer=edi__pb2.ShippingRequest.SerializeToString,
                response_deserializer=edi__pb2.ShippingResponse.FromString,
                )
        self.CreateOrder = channel.unary_unary(
                '/EDIService/CreateOrder',
                request_serializer=edi__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=edi__pb2.CreateOrderResponse.FromString,
                )
        self.CancelOrder = channel.unary_unary(
                '/EDIService/CancelOrder',
                request_serializer=edi__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=edi__pb2.CancelOrderResponse.FromString,
                )


class EDIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateShipping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EDIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateShipping': grpc.unary_stream_rpc_method_handler(
                    servicer.CalculateShipping,
                    request_deserializer=edi__pb2.ShippingRequest.FromString,
                    response_serializer=edi__pb2.ShippingResponse.SerializeToString,
            ),
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=edi__pb2.CreateOrderRequest.FromString,
                    response_serializer=edi__pb2.CreateOrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=edi__pb2.CancelOrderRequest.FromString,
                    response_serializer=edi__pb2.CancelOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EDIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EDIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateShipping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/EDIService/CalculateShipping',
            edi__pb2.ShippingRequest.SerializeToString,
            edi__pb2.ShippingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EDIService/CreateOrder',
            edi__pb2.CreateOrderRequest.SerializeToString,
            edi__pb2.CreateOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EDIService/CancelOrder',
            edi__pb2.CancelOrderRequest.SerializeToString,
            edi__pb2.CancelOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
